name: Set PR merge configuration
description: Set Pull Request merge configuration
repository: MunifTanjim/octoherd-script-set-pr-merge-config
package: octoherd-script-set-pr-merge-config
version: 1.1.0
options:
  - name: merge-commit
    type: boolean
    description: Merge commits
  - name: rebase-merge
    type: boolean
    description: Rebase merging
  - name: squash-merge
    type: boolean
    defaultValue: true
    description: Squash merging
